telegram:
  token: 522816031:AAHLE20HCgQq-OmnUEWCnEBLwEtpeO6Tsgw      # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: true
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: false
discord:
  useNickname: false
  token: MzgxMDk3OTU1ODc4MjQwMjU2.DkXGQg.N36ywVU43FOuqux9ppV9Tpu1clg       # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
bridges:
  - name: Default bridge
    direction: both
    telegram:
      chatId: -1001052152874  # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
    discord:
      serverId: '420247736261279745'         # This ID must be wrapped in single quotes. Example: '244791815503347712'
      channelId: '420247736856739841'       # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
debug: false
